[theme]
# Primary accent color fon interactive elements.

primaryColor = "#d33682"

# Background color for the main content area.
backgroundColor = "#00222b"

# Background color used for the sidebar and most interactive widgets.
secondaryBackgroundColor = "#586e75"

# Color used for almost text.
textColor = "#fff"